grails-samples/grails.org/grails-app/controllers/org/grails/rateable/RatingLinkController.groovy
package org.grails.rateable

import org.grails.plugin.Plugin

class RatingLinkController {
    
    def index = { redirect(action:list,params:params) }

    // the delete, save and update actions only accept POST requests
    static allowedMethods = [delete:'POST', save:'POST', update:'POST']

    def list = {
        params.max = Math.min( params.max ? params.max.toInteger() : 10,  100)
        def list = RatingLink.list(params)
        list.each {
            // only ratings on plugins at the moment...
            def plugin = Plugin.get(it.ratingRef)
            it.metaClass.getPlugin = { -> plugin }
        }
        [ ratingLinks: list, total: RatingLink.count() ]
    }

    def delete = {
        def ratingLinkInstance = RatingLink.get( params.id )
        if(ratingLinkInstance) {
            try {
                ratingLinkInstance.delete()
                flash.message = "RatingLink ${params.id} deleted"
                redirect(action:list)
            }
            catch(org.springframework.dao.DataIntegrityViolationException e) {
                flash.message = "RatingLink ${params.id} could not be deleted"
                redirect(action:list)
            }
        }
        else {
            flash.message = "RatingLink not found with id ${params.id}"
            redirect(action:list)
        }
    }

    def edit = {
        def ratingInstance = Rating.get( params.id )

        if(!ratingInstance) {
            flash.message = "Rating not found with id ${params.id}"
            redirect(action:list)
        }
        else {
            return [ ratingInstance : ratingInstance ]
        }
    }

    def update = {
        def ratingInstance = Rating.get( params.id )
        if(ratingInstance) {
            if(params.version) {
                def version = params.version.toLong()
                if(ratingInstance.version > version) {

                    ratingInstance.errors.rejectValue("version", "rating.optimistic.locking.failure", "Another user has updated this Rating while you were editing.")
                    render(view:'edit',model:[ratingInstance:ratingInstance])
                    return
                }
            }
            ratingInstance.properties = params
            if(!ratingInstance.hasErrors() && ratingInstance.save()) {
                flash.message = "Rating ${params.id} updated"
                redirect(action:list)
            }
            else {
                render(view:'edit',model:[ratingInstance:ratingInstance])
            }
        }
        else {
            flash.message = "Rating not found with id ${params.id}"
            redirect(action:edit,id:params.id)
        }
    }

    def save = {
        def ratingInstance = new Rating(params)
        if(!ratingInstance.hasErrors() && ratingInstance.save()) {
            flash.message = "Rating ${ratingInstance.id} created"
            redirect(action:list)
        }
        else {
            render(view:'create',model:[ratingInstance:ratingInstance])
        }
    }
}

grails-samples/grails.org/grails-app/views/ratingLink/edit.gsp
<%@ page import="org.grails.rateable.Rating" %>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
        <meta name="layout" content="main" />
        <title>Admin: Edit Rating</title>
    </head>
    <body>
        <div class="nav">
            <span class="menuButton"><a class="home" href="${createLinkTo(dir:'admin')}">Home</a></span>
            <span class="menuButton"><g:link controller="ratingLink" class="list" action="list">Rating List</g:link></span>
        </div>
        <div class="body">
            <h1>Edit Rating</h1>
            <g:if test="${flash.message}">
            <div class="message">${flash.message}</div>
            </g:if>
            <g:hasErrors bean="${ratingInstance}">
            <div class="errors">
                <g:renderErrors bean="${ratingInstance}" as="list" />
            </div>
            </g:hasErrors>
            <g:form method="post" >
                <input type="hidden" name="id" value="${ratingInstance?.id}" />
                <input type="hidden" name="version" value="${ratingInstance?.version}" />
                <div class="dialog">
                    <table>
                        <tbody>
                        
                            <tr class="prop">
                                <td valign="top" class="name">
                                    <label for="raterClass">Rater Class:</label>
                                </td>
                                <td valign="top" class="value ${hasErrors(bean:ratingInstance,field:'raterClass','errors')}">
                                    <input type="text" id="raterClass" name="raterClass" value="${fieldValue(bean:ratingInstance,field:'raterClass')}"/>
                                </td>
                            </tr> 
                        
                            <tr class="prop">
                                <td valign="top" class="name">
                                    <label for="raterId">Rater Id:</label>
                                </td>
                                <td valign="top" class="value ${hasErrors(bean:ratingInstance,field:'raterId','errors')}">
                                    <input type="text" id="raterId" name="raterId" value="${fieldValue(bean:ratingInstance,field:'raterId')}" />
                                </td>
                            </tr> 
                        
                            <tr class="prop">
                                <td valign="top" class="name">
                                    <label for="dateCreated">Date Created:</label>
                                </td>
                                <td valign="top" class="value ${hasErrors(bean:ratingInstance,field:'dateCreated','errors')}">
                                    <g:datePicker name="dateCreated" value="${ratingInstance?.dateCreated}" ></g:datePicker>
                                </td>
                            </tr> 
                        
                            <tr class="prop">
                                <td valign="top" class="name">
                                    <label for="lastUpdated">Last Updated:</label>
                                </td>
                                <td valign="top" class="value ${hasErrors(bean:ratingInstance,field:'lastUpdated','errors')}">
                                    <g:datePicker name="lastUpdated" value="${ratingInstance?.lastUpdated}" ></g:datePicker>
                                </td>
                            </tr> 
                        
                            <tr class="prop">
                                <td valign="top" class="name">
                                    <label for="stars">Stars:</label>
                                </td>
                                <td valign="top" class="value ${hasErrors(bean:ratingInstance,field:'stars','errors')}">
                                    <input type="text" id="stars" name="stars" value="${fieldValue(bean:ratingInstance,field:'stars')}" />
                                </td>
                            </tr> 
                        
                            <tr class="prop">
                                <td valign="top" class="name">
                                    <label for="rater">Rater:</label>
                                </td>
                                <td valign="top" class="value ${hasErrors(bean:ratingInstance,field:'rater','errors')}">
                                    
                                </td>
                            </tr> 
                        
                        </tbody>
                    </table>
                </div>
                <div class="buttons">
                    <span class="button"><g:actionSubmit class="save" value="Update" /></span>
                    <span class="button"><g:actionSubmit class="delete" onclick="return confirm('Are you sure?');" value="Delete" /></span>
                </div>
            </g:form>
        </div>
    </body>
</html>

grails-samples/grails.org/grails-app/views/ratingLink/list.gsp
<%@ page import="org.grails.rateable.RatingLink" %>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
        <meta name="layout" content="main" />
        <title>Admin: Rating List</title>
    </head>
    <body>
        <div class="nav">
            <span class="menuButton"><a class="home" href="${createLinkTo(dir:'admin')}">Home</a></span>
        </div>
        <div class="body">
            <h1>RatingLink List</h1>
            <g:if test="${flash.message}">
            <div class="message">${flash.message}</div>
            </g:if>
            <div class="list">
                <table>
                    <thead>
                        <tr>
                        
                   	        <g:sortableColumn property="id" title="Id" />
                        
                   	        <td>Plugin</td>

                   	        <th>Rating</th>
                   	    
                        </tr>
                    </thead>
                    <tbody>
                    <g:each in="${ratingLinks}" status="i" var="ratingLink">
                        <tr class="${(i % 2) == 0 ? 'odd' : 'even'}">
                        
                            <td><g:link action="edit" id="${ratingLink.rating.id}">${fieldValue(bean:ratingLink, field:'id')}</g:link></td>
                        
                            <td><g:link controller='plugin' action='show' params="${[name:ratingLink.plugin.name]}">${ratingLink.plugin.title}</g:link></td>
                        
                            <td>${fieldValue(bean:ratingLink, field:'rating')}</td>
                        
                        </tr>
                    </g:each>
                    </tbody>
                </table>
            </div>
            <div class="paginateButtons">
                <g:paginate total="${total}" />
            </div>
        </div>
    </body>
</html>